### ISSUE TITLE
AN ERROR OCCURRED

### ISSUE THREAD

**Issue by versicherungs-vergleicher** [auphonic/auphonic-mobile#11]
Hallo Georg, ich versuche es in Deutsch, sonst gibt es für mich wahrscheinlich Verständnisprobleme
ich habe mit der Auphonic-IOS App, iPhone5s, iOS 8.1.3 Audiodateien aufgenommen. Meine erste Datei war ca. 27 min. lang, ich habe dort nichts weiter eingegeben und die Produktion ist fehlerfrei durchgelaufen. Das Ergebnis war schonmal richtig toll, wie klar ohne weitere Einstellungen die Ausgabedatei ist - Danke dafür ! ;-))  Jetzt habe ich eine Datei 20:20 min. erzeugt sozusagen meine Nullserie aufgenommen, dann habe ich Metadaten, Name usw. eingegeben, ich habe Kapitelmarken gesetzt - eben viele Daten eingegeben, dann auf Save and start Production - dann kommt der wenig erklärende Fehler oben - ich vermute irgendwo etwas eingegeben zu haben was er nicht will (zuviel, falsche zeichen oder so) - ich könnte den iPhonescreen gern auch aufzeichnen um dir alle Einstellungen zu zeigen, damit du vielleicht siehst wo ich vielleicht Mist gebaut habe... Danke Grüße Carsten

**Comment by versicherungs-vergleicher** [comment]
Uups, jetzt geht es - die Quelle hatte sich scheinbar verstellt, warum auch immer... viel Wirbel um nix...
Danke, für dieses großartige Tool, auch wenn ich es noch nicht ganz verstehe ;-)

**Comment by gholzmann** [comment]
Gut dass es wieder geht!
Wenn du noch nicht so mit Auphonic vertraut bist verwende besser unser Web Interface - da ist alles viel übersichtlicher und stabiler!

**Comment by versicherungs-vergleicher** [comment]
Mach ich Danke, ich werde jetzt üben umd dann wenn alles klappt bestimmt auch über die 2h kommen, die du gerade verschenkst, wenn ich mir überlege wieviel Gedanken ich mir über Technik gemacht habe, die auch sicher bald Anwendung finden - Und jetzt habe ich mit dem iPhone und den Apple Headset mal einfach so eine Episode aufgenommen... Sehr cool, ziemlich klar finde ich - wenn auch der fachmann vielleicht die Nase rümpft -  - wenn ich jetzt noch die Technik verbessere, durch Übung immer mehr lerne... da freu ich mich drauf dann mit podlove publisher, Reaper Ultraschall und was noch alles kommt zu arbeiten - Danke Georg - für das echt geile Tool ! Hammer!
