### ISSUE TITLE
Production error

### ISSUE THREAD

**Issue by eranp** [auphonic/auphonic-mobile#2]
Hi,
The recordings I make (contains chapters) are successfully uploaded and attached to my production, but when I press "save and start production" I get an error message: "AN ERROR OCCURRED/ Please try again or report a bug so we can fix this as soon as possible."
I get this message with several file formats... Please help...
Thanks,
Eran

**Comment by gholzmann** [comment]
Could you please send me the UUID of your production per email? (grh _at_ auphonic _döt_ com)
I have to take a look at the file ...

**Comment by eranp** [comment]
Thank you very much for the quick response. I've sent you the UUID.
Since it happens with every file I record, I've created a new file for you to check. The file is already on the servers (because there's no problem uploading it). If I try to start production within auphonic.com it works perfectly (it seems that the app is causing the problem)
