### ISSUE TITLE
Edit chapters in IOS

### ISSUE THREAD

**Issue by Benjaminsson** [auphonic/auphonic-mobile#3]
I just tap "add chapter" while recording and it works perfect but when i want to change chapter name from the standard "Chapter n" by tapping the chapter name it only changes the first chapter. Whichever chapter i tap i changes the first chapter only. 

Other than that, it works very well. You guys are awesome.

Correction: It creates a new chapter at "00:00:00" every time i try to rename a chapter. It doesn't change the first chapter name. So basically tapping a chapter name is equal to tapping "Add chapter mark"

**Comment by cpojer** [comment]
Hey, I can't reproduce this issue - are you on the latest version (iOS 7 design)?

**Comment by Benjaminsson** [comment]
I'm using iOS 7.0.4. My phone is an iPhone 4s.
I also got an error when trying to start the production with chapters. 

Everything seems to work fine now though. Weird. Maybe my phone just needed a reboot.
