### ISSUE TITLE
App closes when I press start button

### ISSUE THREAD

**Issue by martinvie** [auphonic/auphonic-mobile#4]
I installed the app on my iPhone 3GS, iOS 6.1.3
When I press the Start button, the app closes.
Is my iPhone too old?

**Comment by cpojer** [comment]
hey,

I'm sorry but your iPhone is too old - you'll need at least iOS 7 and I
think that doesn't run on the 3GS :( sorry.

On Thu, Feb 6, 2014 at 11:04 AM, martinvie notifications@github.com wrote:

> I installed the app on my iPhone 3GS, iOS 6.1.3
> When I press the Start button, the app closes.
> Is my iPhone too old?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/auphonic/auphonic-mobile/issues/4
> .

## 

Christoph Pojer
http://cpojer.net
